<?xml version="1.0" encoding="utf-8"?><Database Name="HUWA" Class="huwadbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-NDU24TI\LEOANDRES;Initial Catalog=HUWA;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HUWAConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Account_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Admin" Member="Admins" ThisKey="Account_Id" OtherKey="Account_Id" Type="Admin" />
      <Association Name="Account_Customer" Member="Customers" ThisKey="Account_Id" OtherKey="Account_Id" Type="Customer" />
      <Association Name="Role_Account" Member="Role" ThisKey="Role_Id" OtherKey="Role_Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Admin_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Admin_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Account_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Salary_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url_Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Account_Admin" Member="Account" ThisKey="Account_Id" OtherKey="Account_Id" Type="Account" IsForeignKey="true" />
      <Association Name="Salary_Admin" Member="Salary" ThisKey="Salary_Id" OtherKey="Salary_Id" Type="Salary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="Bill_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Total_Price" Type="System.Decimal" DbType="Decimal(10,6) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bill_Bill_Item" Member="Bill_Items" ThisKey="Bill_Id" OtherKey="Bill_Id" Type="Bill_Item" />
      <Association Name="Customer_Bill" Member="Customer" ThisKey="Customer_Id" OtherKey="Customer_Id" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill_Item" Member="Bill_Items">
    <Type Name="Bill_Item">
      <Column Name="Bill_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Line_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ticket_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bill_Bill_Item" Member="Bill" ThisKey="Bill_Id" OtherKey="Bill_Id" Type="Bill" IsForeignKey="true" />
      <Association Name="Ticket_Bill_Item" Member="Ticket" ThisKey="Ticket_Id" OtherKey="Ticket_Id" Type="Ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bus" Member="Bus">
    <Type Name="Bus">
      <Column Name="Bus_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Company_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bus_Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="License_Plates" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Bus_Seat" Member="Seats" ThisKey="Bus_Id" OtherKey="Bus_Id" Type="Seat" />
      <Association Name="Bus_Trip" Member="Trips" ThisKey="Bus_Id" OtherKey="Bus_Id" Type="Trip" />
      <Association Name="Bus_Type_Bus" Member="Bus_Type" ThisKey="Bus_Type_Id" OtherKey="Bus_Type_Id" Type="Bus_Type" IsForeignKey="true" />
      <Association Name="Company_Bus" Member="Company" ThisKey="Company_Id" OtherKey="Company_Id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bus_Type" Member="Bus_Types">
    <Type Name="Bus_Type">
      <Column Name="Bus_Type_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bus_Type_Name" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Total_Seat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Is_Seat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Bus_Type_Bus" Member="Bus" ThisKey="Bus_Type_Id" OtherKey="Bus_Type_Id" Type="Bus" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="Company_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Company_Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="true" />
      <Column Name="Fax" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Contracted_Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Url_Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Company_Bus" Member="Bus" ThisKey="Company_Id" OtherKey="Company_Id" Type="Bus" />
      <Association Name="Company_Driver" Member="Drivers" ThisKey="Company_Id" OtherKey="Company_Id" Type="Driver" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Customer_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Identication_Number" Type="System.Decimal" DbType="Decimal(9,0)" CanBeNull="true" />
      <Column Name="Account_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Bill" Member="Bills" ThisKey="Customer_Id" OtherKey="Customer_Id" Type="Bill" />
      <Association Name="Account_Customer" Member="Account" ThisKey="Account_Id" OtherKey="Account_Id" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Driver" Member="Drivers">
    <Type Name="Driver">
      <Column Name="Driver_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Driver_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.Decimal" DbType="Decimal(11,0)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Company_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Account_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Salary_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url_Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Driver_Trip" Member="Trips" ThisKey="Driver_Id" OtherKey="Driver_Id" Type="Trip" />
      <Association Name="Company_Driver" Member="Company" ThisKey="Company_Id" OtherKey="Company_Id" Type="Company" IsForeignKey="true" />
      <Association Name="Salary_Driver" Member="Salary" ThisKey="Salary_Id" OtherKey="Salary_Id" Type="Salary" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Role_Name" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Role_Account" Member="Accounts" ThisKey="Role_Id" OtherKey="Role_Id" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.Route" Member="Routes">
    <Type Name="Route">
      <Column Name="Route_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Start_Point" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Def_Point" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trips_Per_Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Route_Trip" Member="Trips" ThisKey="Route_Id" OtherKey="Route_Id" Type="Trip" />
    </Type>
  </Table>
  <Table Name="dbo.Salary" Member="Salaries">
    <Type Name="Salary">
      <Column Name="Salary_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Salary_Wave" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(12,0) NOT NULL" CanBeNull="false" />
      <Association Name="Salary_Admin" Member="Admins" ThisKey="Salary_Id" OtherKey="Salary_Id" Type="Admin" />
      <Association Name="Salary_Driver" Member="Drivers" ThisKey="Salary_Id" OtherKey="Salary_Id" Type="Driver" />
    </Type>
  </Table>
  <Table Name="dbo.Seat" Member="Seats">
    <Type Name="Seat">
      <Column Name="Seat_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Seat_Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Seat_Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bus_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Seat_Seat_Map" Member="Seat_Maps" ThisKey="Seat_Id" OtherKey="Seat_Id" Type="Seat_Map" />
      <Association Name="Seat_Ticket" Member="Tickets" ThisKey="Seat_Id" OtherKey="Seat_Id" Type="Ticket" />
      <Association Name="Bus_Seat" Member="Bus" ThisKey="Bus_Id" OtherKey="Bus_Id" Type="Bus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seat_Map" Member="Seat_Maps">
    <Type Name="Seat_Map">
      <Column Name="Seat_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Trip_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Seat_Seat_Map" Member="Seat" ThisKey="Seat_Id" OtherKey="Seat_Id" Type="Seat" IsForeignKey="true" />
      <Association Name="Trip_Seat_Map" Member="Trip" ThisKey="Trip_Id" OtherKey="Trip_Id" Type="Trip" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="Ticket_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Seat_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Unit_Price" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="Trip_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Ticket_Bill_Item" Member="Bill_Items" ThisKey="Ticket_Id" OtherKey="Ticket_Id" Type="Bill_Item" />
      <Association Name="Seat_Ticket" Member="Seat" ThisKey="Seat_Id" OtherKey="Seat_Id" Type="Seat" IsForeignKey="true" />
      <Association Name="Trip_Ticket" Member="Trip" ThisKey="Trip_Id" OtherKey="Trip_Id" Type="Trip" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trip" Member="Trips">
    <Type Name="Trip">
      <Column Name="Trip_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bus_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Route_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Start_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Driver_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Association Name="Trip_Seat_Map" Member="Seat_Maps" ThisKey="Trip_Id" OtherKey="Trip_Id" Type="Seat_Map" />
      <Association Name="Trip_Ticket" Member="Tickets" ThisKey="Trip_Id" OtherKey="Trip_Id" Type="Ticket" />
      <Association Name="Bus_Trip" Member="Bus" ThisKey="Bus_Id" OtherKey="Bus_Id" Type="Bus" IsForeignKey="true" />
      <Association Name="Driver_Trip" Member="Driver" ThisKey="Driver_Id" OtherKey="Driver_Id" Type="Driver" IsForeignKey="true" />
      <Association Name="Route_Trip" Member="Route" ThisKey="Route_Id" OtherKey="Route_Id" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
</Database>