<?xml version="1.0" encoding="utf-8"?><Database Name="HUWA" Class="huwadbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-LEOANDRES\LEOANDRES;Initial Catalog=HUWA;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HUWAConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Route" Member="Routes">
    <Type Name="Route">
      <Column Name="Route_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Start_Point" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Def_Point" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Trips_Per_Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Seat_Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Route_Trip" Member="Trips" ThisKey="Route_Id" OtherKey="Route_Id" Type="Trip" />
      <Association Name="Seat_Type_Route" Member="Seat_Type" ThisKey="Seat_Type_Id" OtherKey="Seat_Type_Id" Type="Seat_Type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seat" Member="Seats">
    <Type Name="Seat">
      <Column Name="Seat_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Seat_Type_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Seat_Type_Seat" Member="Seat_Type" ThisKey="Seat_Type_Id" OtherKey="Seat_Type_Id" Type="Seat_Type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seat_Type" Member="Seat_Types">
    <Type Name="Seat_Type">
      <Column Name="Seat_Type_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Seat_Type_Route" Member="Routes" ThisKey="Seat_Type_Id" OtherKey="Seat_Type_Id" Type="Route" />
      <Association Name="Seat_Type_Seat" Member="Seats" ThisKey="Seat_Type_Id" OtherKey="Seat_Type_Id" Type="Seat" />
    </Type>
  </Table>
  <Table Name="dbo.Trip" Member="Trips">
    <Type Name="Trip">
      <Column Name="Trip_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Start_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Route_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Route_Trip" Member="Route" ThisKey="Route_Id" OtherKey="Route_Id" Type="Route" IsForeignKey="true" />
    </Type>
  </Table>
</Database>